import type { NextPage } from 'next'
import React from 'react'
import LoginPage from './loginPage'
// import HomePage from './HomePage'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AiFillLinkedin } from "react-icons/ai";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login page</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <LoginPage />
        </div>
      </main>;

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/josias-santos-265319179/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Josias Santos{' '}
          <span className={styles.logo}>
          {/* <h2>< AiFillLinkedin  width={72} height={16} /></h2>  */}
          < AiFillLinkedin  width={100} height={50} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export default Home
